proxy_listen = 0.0.0.0:8000, 0.0.0.0:8443 ssl
admin_listen = 0.0.0.0:8001, 0.0.0.0:8444 ssl

ssl_cert     = /etc/kong/ssl/kong.crt
ssl_cert_key = /etc/kong/ssl/kong.key

admin_ssl_cert     = /etc/kong/ssl/kong.crt
admin_ssl_cert_key = /etc/kong/ssl/kong.key
